version: '3.1'

services:
  nginx1:
    image: nginx:1.17.6-alpine
    container_name: nginx1
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./app/studentui:/usr/share/nginx/html
    ports:
     - 8080:80
    extra_hosts:
    - apihost:10.0.2.15
  nginx2:
    image: nginx:1.17.6-alpine
    container_name: nginx2
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./app/iitjui:/usr/share/nginx/html
    ports:
     - 8081:80
    extra_hosts:
    - apihost:10.0.2.15
